image:
  file: .gitpod.Dockerfile

tasks:
- before: export ROOT_URL=$(gp url 3000)
  init: meteor npm install
  command: meteor
ports:
- port: 3000
  name: meteor
  onOpen: open-preview
- port: 3001
  name: mongoDb
  onOpen: ignore
